name: Pull Request CI

on:
  pull_request:
    types: [opened, edited]
    branches: ["main", "develop"]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Check PR Title
        uses: thehanimo/pr-title-checker@v1.4.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Check PR Description
        uses: transferwise/actions-pr-checker@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_CONTAINS_PATTERN: '.{10,}'
          PR_COMMENT: |
            PR description is mandatory. Please, describe your changes and add any important information that helps to understand better the made changes.
  
