name: PR Actions
on: [pull_request]	
types: [opened, edited, synchronize]	
jobs:
  publish:
  runs-on: ubuntu-latest
     steps:
      - name: Check PR Title
      uses: thehanimo/pr-title-checker@v1.0.0
       with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
